### ISSUE TITLE
using msbuild on Fedora 33

### ISSUE THREAD

**Issue by albfan** [mono/linux-packaging-msbuild#18]
### Steps to reproduce

I'm able to use xbuild on Fedora 33 but seems there's no msbuild package.

After build this repos succesfully I created a `/usr/bin/msbuild` with:

```
#!/bin/sh
MONO_GC_PARAMS="nursery-size=64m,$MONO_GC_PARAMS" exec /usr/bin/mono --assembly-loader=strict $MONO_OPTIONS /home/alberto/projects/csharp/linux-packaging-msbuild/artifacts/bin/MSBuild/Debug/netcoreapp2.1/MSBuild.dll "$@"
```

But seems that is not a valid executable. I'm trying to build opentk.

### Expected behavior

Build the project

### Actual behavior

```
MSBUILD : error MSB1021: No se puede crear una instancia del registrador. Could not load file or assembly 'System.Runtime.Loader, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Modificador: Fake.MsBuildLogger+ErrorLogger,/home/alberto/projects/csharp/official-opentk/packages/FAKE/tools/FakeLib.dll
```

MSbuild.dll not working as msbuild executable

### Environment data

$ msbuild /version
Microsoft (R) Build Engine versión 16.6.0+bac117c40 para .NET Core
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

OS info:

Fedora 33

**Comment by quentincaffeino** [comment]
Same problem with Fedora 34, msbuild is not present

**Comment by albfan** [comment]
@quentincaffeino looks `dotnet msbuild` is the solution right?

**Comment by quentincaffeino** [comment]
@albfan , I'm not a c# dev and I don't know much about differences between mono and dotnet so I'm might be wrong. I wouldn't call this a solution since one might want to use mono's version of msbuild. But it works
