### ISSUE TITLE
[README] Windows support

### ISSUE THREAD

**Issue by ShalokShalom** [mono/linux-packaging-msbuild#2]
This Readme feels a little bit confusing. Why .exe and Visual Studio?

**Comment by ShalokShalom** [comment]
There is another repository, with the same README: https://github.com/mono/msbuild

There are a lot of different, similar named repos here on mono. So, somebody might clean that up.

**Comment by akoeplinger** [comment]
This repository is specifically for building the Linux packages for msbuild, i.e. everything inside of [debian/](https://github.com/mono/linux-packaging-msbuild/tree/master/debian).

I'd suggest you file your suggestion on https://github.com/mono/msbuild, thanks!

**Comment by ShalokShalom** [comment]
So how can make this README any sense?

**Comment by akoeplinger** [comment]
The readme is just copied from the upstream repository, it doesn't really apply here.

**Comment by ShalokShalom** [comment]
So delete it?
