### ISSUE TITLE
Broken version 

### ISSUE THREAD

**Issue by kekekeks** [mono/linux-packaging-msbuild#5]
I'm getting 
```
 error : Version 2.1.302 of the .NET Core SDK requires at least version 15.3.0 of MSBuild. The current available version of MSBuild is 15.1.8.0. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.`
```
when trying to build .NET Core application with Mono version of MSBuild. That didn't happen with 15.6 which was properly reporting it's version.

**Comment by directhex** [comment]
https://jenkins.mono-project.com/view/Releases/job/ng-release-generate-debian-packages/1319/

**Comment by directhex** [comment]
https://jenkins.mono-project.com/view/Releases/job/ng-release-generate-rpm-packages/870/

**Comment by directhex** [comment]
Built. Promoting to stable/vs
